### ISSUE TITLE
Submit of new paper

### ISSUE THREAD

**Issue by Midnight93** [ch-shin/awesome-data-poisoning#1]
Paper title:

[Just How Toxic is Data Poisoning? A Unified Benchmark for Backdoor and Data Poisoning Attacks
](https://arxiv.org/pdf/2006.12557.pdf#page=9&zoom=100,0,0)

Repo Github:

https://github.com/aks2203/poisoning-benchmark

Authors:

Avi Schwarzschild, Micah Goldblum, Arjun Gupta, John P. Dickerson,  Tom Goldstein

**Comment by ch-shin** [comment]
Thanks!
